language: go

go:
  - 1.10.x

# skip the install step. don't `go get` deps. only build with code in vendor/
install: true

notifications:
  email: false

# install code checkers
before_script:
  - cd vendor/github.com/golang/lint/golint
  - go install
  - cd -
  - cd vendor/honnef.co/go/tools/cmd/megacheck
  - go install
  - cd -
  - cd vendor/github.com/fzipp/gocyclo
  - go install
  - cd -

script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - test -z $(gofmt -s -l ${GO_FILES})
  - go test -v -race ./...
  - go vet ./...
  - megacheck ./...
  # golint ./... doesn't ignore vendor/ for some dumb reason
  - golint -set_exit_status $(go list ./... | grep -v /vendor/)
  - gocyclo -over 10 ${GO_FILES}
