required = [
  "github.com/golangci/golangci-lint/cmd/golangci-lint",
]

[[constraint]]
  name = "github.com/golangci/golangci-lint"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "^0.1.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
